package com.educache.backend.models;

import jakarta.persistence.*;
import java.util.Date;

@Entity                       // Marks the class as a JPA entity (a table in the database).
@Table(name = "assessments")  // Specifies that this entity maps to the "assessments" table in the database.
public class Assessment {

    @Id                                        // Marks this field as the primary key of the table.
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    // Specifies that the ID is auto-generated by the database (auto-increment).
    private Long id;

    private String assessmentType;              // A field to store the type of assessment (e.g., quiz, exam).
    private double score;                        // A field to store the score obtained in the assessment.

    @Temporal(TemporalType.TIMESTAMP)          // Indicates that this field should be treated as a date and time.
    private Date dateOfAssessment;              // A field to store the date of the assessment.

    @ManyToOne                                 // Establishes a many-to-one relationship with the Student entity.
    @JoinColumn(name = "student_id")           // This column will act as the foreign key in the assessments table.
    private Student student;

    // Set the dateOfAssessment to the current date before the entity is created
    @PrePersist
    protected void onCreate() {
        dateOfAssessment = new Date();          // Set dateOfAssessment to the current date and time.
    }

    // Getters and setters for all the fields
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAssessmentType() {
        return assessmentType;
    }

    public void setAssessmentType(String assessmentType) {
        this.assessmentType = assessmentType;
    }

    public double getScore() {
        return score;
    }

    public void setScore(double score) {
        this.score = score;
    }

    public Date getDateOfAssessment() {
        return dateOfAssessment;
    }

    public void setDateOfAssessment(Date dateOfAssessment) {
        this.dateOfAssessment = dateOfAssessment;
    }

    public Student getStudent() {
        return student;
    }

    public void setStudent(Student student) {
        this.student = student;
    }
}
